extension DefaultGlossary {
    static let ministryEntries: [GlossaryEntry] = [
        GlossaryEntry(source: "圣灵", target: "the Holy Spirit", enforcement: .required),
        GlossaryEntry(source: "圣父", target: "God the Father"),
        GlossaryEntry(source: "圣子", target: "God the Son"),
        GlossaryEntry(
            source: "救恩",
            target: "salvation",
            recognitionAliases: ["休恩"],
            targetVariants: ["saved", "saving"],
            enforcement: .required),
        GlossaryEntry(
            source: "恩典",
            target: "grace",
            targetVariants: ["gracious"],
            enforcement: .required),
        GlossaryEntry(
            source: "称义",
            target: "justification",
            targetVariants: ["justified", "justify", "justifies"]),
        GlossaryEntry(
            source: "在圣灵里成圣",
            target: "be sanctified in the Holy Spirit"),
        GlossaryEntry(
            source: "成圣",
            target: "sanctification",
            targetVariants: ["sanctified", "sanctify", "sanctifies"]),
        GlossaryEntry(
            source: "重生",
            target: "regeneration",
            targetVariants: ["born again", "new birth"]),
        GlossaryEntry(source: "赎罪", target: "atonement", enforcement: .required),
        GlossaryEntry(source: "悔改", target: "repentance"),
        GlossaryEntry(source: "信心", target: "faith"),
        GlossaryEntry(source: "罪性", target: "sinful nature"),
        GlossaryEntry(source: "原罪", target: "original sin"),
        GlossaryEntry(source: "十字架", target: "the cross"),
        GlossaryEntry(source: "复活", target: "resurrection"),
        GlossaryEntry(
            source: "基督身体的复活",
            target: "Christ's bodily resurrection",
            targetVariants: ["bodily resurrection"]),
        GlossaryEntry(
            source: "荣耀",
            target: "glorify",
            targetVariants: ["glorifies", "glorified", "glory"]),
        GlossaryEntry(
            source: "荣耀自己",
            target: "glorify Himself",
            sourceAliases: ["使自己得荣耀"],
            targetVariants: ["glorifies Himself"],
            enforcement: .required),
        GlossaryEntry(
            source: "荣耀基督",
            target: "glorify Christ",
            sourceAliases: ["使基督得荣耀", "使基督得着荣耀"],
            targetVariants: ["glorifies Christ"],
            enforcement: .required),
        GlossaryEntry(
            source: "传扬",
            target: "preaching",
            targetVariants: ["preach", "proclaim", "proclamation"]),
        GlossaryEntry(source: "徒然", target: "in vain", targetVariants: ["vain"]),
        GlossaryEntry(source: "永生", target: "eternal life"),
        GlossaryEntry(source: "福音", target: "the gospel"),
        GlossaryEntry(source: "圣经", target: "Scripture"),
        GlossaryEntry(source: "耶稣基督", target: "Jesus Christ"),
        GlossaryEntry(source: "教会", target: "the church", targetVariants: ["church"]),
        GlossaryEntry(source: "门徒", target: "disciple"),
        GlossaryEntry(source: "使徒", target: "apostle"),
        GlossaryEntry(source: "先知", target: "prophet"),
        GlossaryEntry(source: "牧者", target: "pastor"),
        GlossaryEntry(source: "长老", target: "elder"),
        GlossaryEntry(source: "执事", target: "deacon"),
        GlossaryEntry(source: "敬拜", target: "worship"),
        GlossaryEntry(
            source: "祷告",
            target: "prayer",
            targetVariants: ["pray", "prays", "praying"],
            enforcement: .required),
        GlossaryEntry(
            source: "赞美",
            target: "praise",
            targetVariants: ["praises", "praising"],
            enforcement: .required),
        GlossaryEntry(source: "律法", target: "the law"),
        GlossaryEntry(source: "盟约", target: "covenant"),
        GlossaryEntry(source: "应许", target: "promise"),
        GlossaryEntry(source: "拣选", target: "election"),
        GlossaryEntry(source: "预定", target: "predestination"),
        GlossaryEntry(source: "属灵恩赐", target: "spiritual gift"),
        GlossaryEntry(source: "方言", target: "tongues"),
        GlossaryEntry(
            source: "宝血",
            target: "the blood of Christ",
            targetVariants: ["His blood", "through His blood"]),
        GlossaryEntry(source: "属灵", target: "spiritual"),
        GlossaryEntry(source: "肢体", target: "fellow member of the body of Christ"),
        GlossaryEntry(
            source: "事奉",
            target: "ministry",
            targetVariants: ["serve", "serving", "service"]),
        GlossaryEntry(
            source: "圣餐",
            target: "the Lord's Supper",
            targetVariants: ["Holy Communion", "Communion"],
            enforcement: .required),
        GlossaryEntry(
            source: "洗礼",
            target: "baptism",
            sourceAliases: ["受浸"],
            targetVariants: ["baptized", "baptize"]),
    ]
}
